package com.robwettach.webdiplomacy.diff;

import static java.util.stream.Collectors.toList;

import com.google.common.collect.ImmutableList;
import java.util.List;

/**
 * Checks for all types of diffs.
 *
 * <p>Configures multiple {@link DiffChecker diff checkers} including:
 * <ul>
 *     <li>{@link PhaseChecker}</li>
 *     <li>{@link HourRemainingChecker}</li>
 *     <li>{@link PausedChecker}</li>
 *     <li>{@link OrderChecker}</li>
 *     <li>{@link DefeatedChecker}</li>
 *     <li>{@link VoteChecker}</li>
 * </ul>
 */
public class DiffCheckers {
    private static final List<DiffChecker> CHECKERS = ImmutableList.of(
            new PhaseChecker(),
            new HourRemainingChecker(),
            new PausedChecker(),
            new OrderChecker(),
            new DefeatedChecker(),
            new VoteChecker(),
            new FinishedChecker());

    /**
     * Check all of the available {@link DiffChecker}s.
     *
     * @param previous The previous game state
     * @param current The latest game state
     * @return The list of {@link Diff}s generated by all of the checkers
     */
    public static List<Diff> check(Snapshot previous, Snapshot current) {
        return CHECKERS.stream()
                .flatMap(c -> c.check(previous, current).stream())
                .collect(toList());
    }
}
